# Generated by Django 3.2 on 2024-12-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_unique_username_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_email',
        ),
    ]
