# Generated by Django 3.2 on 2024-12-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20241204_1523'),
        ('reviews', '0006_alter_title_rating'),
    ]

    operations = [
    ]
